# wrangler.toml
name = "kidzo-website"
compatibility_date = "2024-04-29" # Use a recent date

# The [site] section is typically not needed for Next.js apps using the Cloudflare adapter
# Cloudflare Pages automatically detects and handles Next.js builds

[build]
command = "pnpm build"

# Optional: Add environment variables if needed
# [vars]
# MY_VAR = "some_value"

# Optional: Add D1 database bindings if using a database
# [[d1_databases]]
# binding = "DB" # i.e. env.DB
# database_name = "kidzo-db"
# database_id = "<YOUR_DB_ID>"
# preview_database_id = "<YOUR_PREVIEW_DB_ID>"

